### PR TITLE
Path update

### PR DESCRIPTION
**Pull request by harshmittal2210**
To Disable Energy Star and Screensaver path should be:

nano ~/.config/lxsession/LXDE/autostart

not 
nano ~/.config/lxsession/LXDE-pi/autostart

### CODE REVIEW

**Comment by lovettchris** [comment]
Not according to [this thread ](https://www.raspberrypi.org/forums/viewtopic.php?f=91&t=131760) on raspberry pi forums, it says:

"should have been "/LXDE-pi/" rather than "/LXDE/". Before Raspbian started including the users autostart (and switched from LXDE to LXDE-pi) you had to create your own "/lxsession/LXDE/autostart" to override the one at "/etc/xdg/". If you had used "nano ~/.config/lxsession/LXDE-pi/autostart" you would have been editing the correct autostart, but using "/LXDE/" it created a new file instead, but of course it won't use it."

**Comment by lovettchris** [comment]
More [confirmation here ](https://www.raspberrypi.org/forums/viewtopic.php?p=697761)that LXDE-pi is the new name.  You can check this log file to see what config file is being used:
```
/home/pi/.cache/lxsession/LXDE-pi/run.log
```
mine says:
```
** Message: utils.vala:68: User config used : /home/pi/.config/lxsession/LXDE-pi/autostart
```
Interestingly this log also says:
```
** (lxsession:480): WARNING **: app.vala:86: Failed to execute child process "xscreensaver" (No such file or directory)
```

**Comment by harshmittal2210** [comment]
I am a bit confused. I have the following directories.
>pi@raspberrypi:~/.config/lxsession $ ls
>> LXDE


>pi@raspberrypi:~/.cache/lxsession $ ls
>>LXDE        LXDE-pi

So this means should I create LXDE-pi in /.config/lxsession ?
Also in my run.log for both LXDE and LXDE-pi i have no message for *User config used*, but yes xscreensaver warning message is there.

**Comment by lovettchris** [comment]
I take it you have two different raspberry pi devices then? one with LXDE and one with both?  What is the "lsb_release -a" output from each of these?

**Comment by lovettchris** [comment]
closed due to inactivity

**Pull request closed without merging**
