### PR TITLE
ctest command edit

### PR DESCRIPTION
**Pull request by harshmittal2210**
If only ctest is entered then  Test not available without configuration.  (Missing "-C <config>"?) error is shown for each test case and no test case are run 
0% tests passed, 42 tests failed out of 42

Total Test time (real) =   1.83 sec

### CODE REVIEW

**Comment by kernhanda** [comment]
I would prefer if it was stated that the extra argument is needed when building with VS.

**Comment by harshmittal2210** [comment]
@kernhanda the extra argument is needed when building with VS only. If the steps for installation are followed using this link. This error is shown.

**Comment by harshmittal2210** [comment]
I have updated the changes, please check if this is what you were suggesting.

**Comment by kernhanda** [comment]
The instructions have been fixed to provide different instructions for Windows. Thanks for pointing this out!

**Pull request closed without merging**
