### PR TITLE
Fix link to gallery.

### PR DESCRIPTION
**Pull request by awf**
Suggested fix - don't know if this is optimal.

### CODE REVIEW

**Comment by lovettchris** [comment]
Thanks for your pull request, but I'm finding the gallery link works fine without the "index.md" part and in fact it does not work with "index.md" because of the page generation that happens in GitHub Pages, the index.md actually turns into "index.html".  What system configuration are you having trouble with?

image

**Comment by awf** [comment]
Ah, perhaps I'm doing an unexpected thing: I visited https://github.com/microsoft/ELL/blob/master/docs/index.md directly.

**Comment by lovettchris** [comment]
Ah, yes, unfortunately we can't make both work, the "docs" folder is expected to be browsed from the GitHub pages site at https://microsoft.github.io/ELL/

**Comment by awf** [comment]
Got it, closing...

**Pull request closed without merging**
